# Cloudflare Pages Configuration
name = "tmp-share-media-srv-kkk"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# KV Namespace binding pour les métadonnées
[[kv_namespaces]]
binding = "METADATA_KV"
id = "1bb2f71ed4d94aa6977556d0ce09d9a0"

# R2 Bucket binding pour le stockage des fichiers
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "flash-share-data-storage"

[env.production]
# Plus besoin de variables d'environnement R2, on utilise les bindings natifs maintenant!
